In [1]:
import pandas as p 
import numpy as np
df = p.read_csv("Social_Network_Adds.csv")
df.head()

User ID  Age  EstimatedSalary  Purchased  Gender
0  15624510   19            19000          0    Male
1  15810944   35            20000          0    Male
2  15668575   26            43000          0  Female
3  15603246   27            57000          0  Female
4  15804002   19            76000          0    Male

In [2]:
import pandas as p 
import numpy as np
import matplotlib.pyplot as plt
dataset = p.read_csv("Social_Network_Adds.csv")
dataset.head()

User ID  Age  EstimatedSalary  Purchased  Gender
0  15624510   19            19000          0    Male
1  15810944   35            20000          0    Male
2  15668575   26            43000          0  Female
3  15603246   27            57000          0  Female
4  15804002   19            76000          0    Male

In [3]:
print(dataset.shape)

(400, 5)


In [4]:
import pandas as p 
import numpy as np
import matplotlib.pyplot as plt
dataset = p.read_csv("Social_Network_Adds.csv")
dataset.head()


User ID  Age  EstimatedSalary  Purchased  Gender
0  15624510   19            19000          0    Male
1  15810944   35            20000          0    Male
2  15668575   26            43000          0  Female
3  15603246   27            57000          0  Female
4  15804002   19            76000          0    Male

In [5]:
dataset['Gender'] = dataset.Gender.map({'Male':1,'Female':0})

In [6]:
# input
x = p.DataFrame(dataset.iloc[:, :-1])

# output
y = p.DataFrame(dataset.iloc[:, -1])

In [7]:
x


User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]

In [8]:
y

Gender
0         1
1         1
2         0
3         0
4         1
..      ...
395       0
396       1
397       0
398       1
399       0

[400 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=1)


In [10]:
cols = xtrain.columns

In [11]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)

print (xtrain[0:10, :])

[[ 0.06699777 -0.80330081 -1.19121795 -0.72876641]
 [-1.32816737  0.75697997 -1.36859801  1.3721818 ]
 [ 0.73196481  0.85449752  1.43991958  1.3721818 ]
 [ 0.14640285 -0.51074816 -1.48685138 -0.72876641]
 [-0.13465464 -1.48592365  0.37563923 -0.72876641]
 [-0.29034596 -1.19337101  0.55301929 -0.72876641]
 [-0.33217181  1.04953262 -1.04340124  1.3721818 ]
 [-0.51946921 -0.21819552 -0.30431766 -0.72876641]
 [-1.41882255  0.95201507 -1.33903467  1.3721818 ]
 [ 0.70674956 -1.09585346 -1.07296458 -0.72876641]]


In [12]:
xtrain = p.DataFrame(xtrain, columns=[cols])

In [13]:
xtest = p.DataFrame(xtest, columns=[cols])

In [14]:
xtrain.head()

User ID       Age EstimatedSalary Purchased
0  0.066998 -0.803301       -1.191218 -0.728766
1 -1.328167  0.756980       -1.368598  1.372182
2  0.731965  0.854498        1.439920  1.372182
3  0.146403 -0.510748       -1.486851 -0.728766
4 -0.134655 -1.485924        0.375639 -0.728766

In [15]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(xtrain, ytrain)


/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(
/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [16]:
y_pred = classifier.predict(xtest)

/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  warnings.warn(


In [17]:
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [18]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(ytest, y_pred)
print ("Confusion Matrix : \n", cm)


Confusion Matrix : 
 [[26 18]
 [17 19]]


In [19]:
from sklearn.metrics import accuracy_score

print ("Accuracy : ", accuracy_score(ytest, y_pred))


Accuracy :  0.5625


In [20]:
from sklearn.metrics import classification_report
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.60      0.59      0.60        44
           1       0.51      0.53      0.52        36

    accuracy                           0.56        80
   macro avg       0.56      0.56      0.56        80
weighted avg       0.56      0.56      0.56        80



In [35]:
from matplotlib.colors import ListedColormap

X_set, y_set = xtest, ytest
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1,stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1,stop = X_set[:, 1].max() + 1, step = 0.01))

plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape), 
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))

plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())

for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],c = ListedColormap(('red', 'green'))(i), label = j)
    
plt.title('Classifier (Test set)')
plt.xlabel('Gender')
plt.ylabel('Age')
plt.legend()
plt.show()


InvalidIndexError: (slice(None, None, None), 0)